# Generated by Django 5.2.7 on 2025-11-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('codigo_livro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título do livro', max_length=100)),
                ('autor', models.CharField(help_text='Autor do livro', max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do livro', max_digits=10)),
            ],
        ),
    ]
